name: Automated checks (main)

on:
  push:
    branches: [main]

jobs:
  code-coverage:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    permissions:
      contents: write
      pages: write
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-badges
      cancel-in-progress: true

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          path: "./repo"

      - name: Checkout GH-Pages
        uses: actions/checkout@v4
        with:
          ref: "gh-pages"
          path: "./gh-pages"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install
        run: |
          cd repo
          npm ci

      - name: Run tests with coverage
        run: |
          cd repo
          npm run test-with-coverage

      - run: |
          cd repo
          npm i coverage-badges-cli -g
      - run: |
          cd repo
          npx coverage-badges --source reports/coverage-summary.json --output ./../gh-pages/coverage-badge.svg --label="Code Coverage"

      - run: |
          cd gh-pages
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *
          git commit -m "Automated gh-pages content update"
          git push

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./gh-pages"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
